# Generated by Django 4.0.3 on 2022-04-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_auth_token', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('refresh_token', models.CharField(max_length=150)),
                ('access_token', models.CharField(max_length=150)),
                ('expires_in', models.DateTimeField()),
                ('token_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='dave', max_length=60, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='temp_code',
            field=models.CharField(default='', max_length=512),
        ),
    ]
