# Generated by Django 4.0.3 on 2022-04-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_spotifytoken_remove_user_username_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes_count', models.IntegerField(default=0)),
                ('downvotes_count', models.IntegerField(default=0)),
                ('votes_total', models.IntegerField(default=0)),
                ('downvotes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.downvote')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('scores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.score')),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Wasabia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('scores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.score')),
                ('songs', models.ManyToManyField(related_name='wasabias', to='workshop.song')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='upvotes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.upvote'),
        ),
        migrations.AddField(
            model_name='user',
            name='downvotes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.downvote'),
        ),
        migrations.AddField(
            model_name='user',
            name='upvotes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.upvote'),
        ),
        migrations.AddField(
            model_name='user',
            name='wasabias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.wasabia'),
        ),
    ]
