# Generated by Django 4.0.3 on 2022-04-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_remove_user_username_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='session_id',
            new_name='user_auth_token',
        ),
    ]
