# Generated by Django 4.0.3 on 2022-04-30 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_downvote_score_song_upvote_wasabia_score_upvotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='temp_code',
        ),
        migrations.AlterField(
            model_name='score',
            name='downvotes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.downvote'),
        ),
        migrations.AlterField(
            model_name='score',
            name='upvotes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.upvote'),
        ),
    ]
