# Generated by Django 4.0.3 on 2022-04-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_rename_session_id_spotifytoken_user_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_code',
            field=models.CharField(default='', max_length=512),
        ),
    ]
