# Generated by Django 4.0.3 on 2022-04-30 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_remove_user_temp_code_alter_score_downvotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='score',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='downvote',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downvotes', to='workshop.score'),
        ),
        migrations.AddField(
            model_name='upvote',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='workshop.score'),
        ),
    ]
