# Generated by Django 4.0.3 on 2022-04-30 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_remove_score_downvotes_remove_score_upvotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='wasabia',
            name='scores',
        ),
        migrations.AddField(
            model_name='score',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='workshop.song'),
        ),
        migrations.AddField(
            model_name='score',
            name='wasabia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='workshop.wasabia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='downvotes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='workshop.downvote'),
        ),
        migrations.AlterField(
            model_name='user',
            name='upvotes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='workshop.upvote'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wasabias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='workshop.wasabia'),
        ),
    ]
