# Generated by Django 4.0.3 on 2022-04-30 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_remove_song_scores_remove_wasabia_scores_score_song_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wasabias',
        ),
        migrations.AddField(
            model_name='downvote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='upvote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wasabia',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wasabias', to=settings.AUTH_USER_MODEL),
        ),
    ]
