# Generated by Django 4.0.3 on 2022-04-30 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_remove_user_downvotes_remove_user_upvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downvote',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvotes', to='workshop.score'),
        ),
        migrations.AlterField(
            model_name='downvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='workshop.song'),
        ),
        migrations.AlterField(
            model_name='score',
            name='wasabia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='workshop.wasabia'),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='workshop.score'),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wasabia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wasabias', to=settings.AUTH_USER_MODEL),
        ),
    ]
